src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['posts','categories'])]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Groups(['posts', 'categories'])]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['posts','categories'])]
    private ?string $resume = null;

    #[ORM\Column]
    #[Groups(['posts'])]
    private ?bool $is_active = null;

    #[ORM\Column]
    #[Groups(['posts'])]
    private ?bool $is_offer = null;

    #[ORM\Column]
    #[Groups(['posts','categories'])]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['posts'])]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'post')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['posts'])]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'post')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['posts','categories'])]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    #[Groups(['posts', 'comments'])]
    private Collection $comments;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['posts','categories'])]
    private ?City $city = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue()
    {
        $this->published_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): static
    {
        $this->resume = $resume;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function isIsOffer(): ?bool
    {
        return $this->is_offer;
    }

    public function setIsOffer(bool $is_offer): static
    {
        $this->is_offer = $is_offer;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeImmutable $published_at): static
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): static
    {
        $this->city = $city;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\City;
use App\Entity\Post;
use App\Entity\User;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre'
            ])
            ->add('resume', TextareaType::class, [
                'label' => 'Résumé'
            ])
            ->add('is_active', ChoiceType::class, [
                'label' => 'Active',
                'choices' => [
                    'Oui' => true,
                    'Non' => false
                ],
            ])
            ->add('is_offer', ChoiceType::class, [
                'label' => 'Offre/Demande',
                'choices' => [
                    'Offre' => true,
                    'Demande' => false
                ],
            ])
            ->add('category', EntityType::class, [
                'label' => 'Catégorie',
                'class' => Category::class,
                'choice_label' => 'name',
            ])
            ->add('user', EntityType::class, [
                'label' => 'Utilisateur',
                'class' => User::class,
                'choice_label' => 'alias',
            ])
            ->add('city', EntityType::class, [
                'label' => 'Ville',
                'class' => City::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/Api/PostController.php
<?php

namespace App\Controller\Api;

use App\Entity\City;
use App\Entity\Post;
use App\Entity\User;
use App\Entity\Category;
use App\Repository\PostRepository;
use Symfony\Component\Mailer\Mailer;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Serializer\Exception\NotEncodableValueException;

#[Route('/api')]
class PostController extends AbstractController
{
    #[Route('/post', name: 'app_api_post', methods: ['GET'])]
    public function index(PostRepository $post): JsonResponse
    {
        $posts = $post->findAll();

        return $this->json($posts, Response::HTTP_OK, [], ['groups' => 'posts']);
    }

    #[Route('/post/{id}', name: 'app_api_post_show', methods: ['GET'])]
    public function show(PostRepository $post, int $id): JsonResponse
    {
        $post = $post->find($id);

        return $this->json($post, Response::HTTP_OK, [], ['groups' => 'posts']);
    }

    #[Route('/post', name: 'app_api_post_new', methods: ['POST'])]
    public function new(EntityManagerInterface $manager, Request $request, SerializerInterface $serializer, ValidatorInterface $validator): JsonResponse
    {

        $data = json_decode($request->getContent(), true);

        try {
            $post = $serializer->deserialize($request->getContent(), Post::class, 'json', [
                AbstractNormalizer::IGNORED_ATTRIBUTES => ['category', 'city', 'user']
            ]);
        } catch (NotEncodableValueException) {
            return $this->json(['error' => "Il semble y avoir un problème !"], Response::HTTP_BAD_REQUEST);
        }

        $errors = $validator->validate($post);

        if (count($errors) > 0) {

            foreach ($errors as $error) {
                $dataErrors[$error->getPropertyPath()][] = $error->getMessage();
            }

            return $this->json($errors, Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        $user = $this->getUser();
        \dump($user);

        if (!$user) {
            return $this->json(['error' => "Vous devez être connecté pour publier une annonce."], Response::HTTP_UNAUTHORIZED);
        }

        $categoryId = $data['category'];
        $cityId = $data['city'];

        $city = $manager->getRepository(City::class)->find($cityId);
        $category = $manager->getRepository(Category::class)->find($categoryId);
        $post->setCategory($category);
        $post->setCity($city);
        $post->setUser($user);

        $manager->persist($post);
        $manager->flush();

        return $this->json(['message' => 'Votre annonce a bien été publiée.'], Response::HTTP_CREATED, [], ['groups' => 'posts']);
    }

    #[Route('/post/city/{id}', name: 'app_api_post_city', methods: ['GET'])]
    public function showByCity(PostRepository $post, int $id): JsonResponse
    {
        $posts = $post->findBy(['city' => $id]);

        return $this->json($posts, Response::HTTP_OK, [], ['groups' => 'posts']);
    }

    #[Route('/post/category/{id}', name: 'app_api_post_category', methods: ['GET'])]
    public function showByCategory(PostRepository $post, int $id): JsonResponse
    {
        $posts = $post->findBy(['category' => $id]);

        return $this->json($posts, Response::HTTP_OK, [], ['groups' => 'posts']);
    }

    #[Route('/post/{id}/mailer', name: 'app_api_post_mailer', methods: ['POST'])]
    public function sendEmail(EntityManagerInterface $manager, Request $request, ValidatorInterface $validator, Post $post, MailerInterface $mailer): JsonResponse
    {
        //!TODO recupération des données front
        $data = json_decode($request->getContent(), true);
        /** @var User $user */
        $user = $this->getUser();
        $senderEmail = $user->getEmail();
        $recipientEmail = $post->getUser()->getEmail();
       
        // Text, Email du destinataire ,
        //!TODO vérification des données via le validator

        $constraints = new Assert\Collection([
            'text' => [
                new Assert\NotBlank(),
                new Assert\Length(
                    min:5,
                    max:255,
                    minMessage: 'Your first name must be at least {{ limit }} characters long',
                    maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
                )
            ],
        ]);

        // validate data
        $errors = $validator->validate($data, $constraints);
        if (count($errors) > 0) {
            return $this->json($errors, Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        //?TODO envoi du mail
        $email = (new TemplatedEmail())
        ->from('heyvoisin.off@gmail.com')
        ->to($recipientEmail)
        ->subject('Sending emails is fun again!')

        // path of the Twig template to render
        ->htmlTemplate('email/mail.html.twig')

        // pass variables (name => value) to the template
        ->context([
        'expiration_date' => new \DateTime('+7 days'),
        'text' => $data['text'],
        'senderEmail' => $senderEmail,
        'postTitle' => $post->getTitle(),
        'senderUsername' => $user->getAlias(),
        ]);
        
        $mailer->send($email);
        return $this->json($post, Response::HTTP_OK, [], ['groups' => 'posts']);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Security\Voter\PostVoter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/post')]
class PostController extends AbstractController
{
    #[Route('/', name: 'app_post_index', methods: ['GET'])]
    #[IsGranted('ROLE_MODERATOR')]
    public function index(PostRepository $post, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $post->paginationQuery(),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('post/index.html.twig', [
            'pagination' => $pagination,            
        ]);
    }

    #[Route('/new', name: 'app_post_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {   
        $post = new Post();
        $post->setPublishedAt(new \DateTimeImmutable());
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash(
                'success', 
                'Votre annonce a bien été créée'
            );

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_show', methods: ['GET'])]
    #[IsGranted('ROLE_MODERATOR')]
    public function show(Post $post): Response
    {
        return $this->render('post/show.html.twig', [
            'post' => $post,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_post_edit', methods: ['GET','POST','PUT'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setUpdatedAt(new \DateTimeImmutable());
            $entityManager->flush();

            $this->addFlash(
                'warning', 
                'Votre annonce a bien été modifiée'
            );

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    #[IsGranted('ROLE_MODERATOR')]
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();

            $this->addFlash(
                'danger', 
                'Votre annonce a bien été supprimée'
            );
        }

        return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('app_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette publication ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-danger rounded-pill text-light">Supprimer</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success m-1 rounded-pill">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une publication
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="mt-5 bg-secondary bg-gradient rounded-5 p-3 text-light text-center">Modifier la publication
			<span class="badge rounded-pill text-bg-success">
				{{ post.id }}
			</span>
		</h1>
		{{ include('post/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

		<a href="{{ path('app_post_index') }}" class="btn btn-secondary m-1 btn-sm rounded-pill">Retour</a>

		{{ include('post/_delete_form.html.twig') }}
	</div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des publications
{% endblock %}

{% block body %}
	<div class="container col-9">

		{% include "fragments/_flash_message.html.twig" %}

		<h1 class="mt-5 bg-secondary bg-gradient rounded-top-5 p-3 text-light text-center mb-0">Liste des publications
			<a href="{{ path('app_post_new') }}" class="btn btn-success bg-gradient shadow btn-sm rounded-pill fw-bold">Ajouter une publication</a>
		</h1>

		<table class="table align-middle vertical-align-middle text-center table-borderless table-striped table-sm shadow">
			<thead class="table-group-divider text-center text-nowrap table-warning">
				<tr>
					<th class="fw-bold">
						<span class="badge bg-secondary rounded-pill">#</span>
					</th>
					<th>Titre</th>
					{# <th>Contenu</th> #}
					<th>Ville</th>
					<th>Catégorie</th>
					<th>Active</th>
					<th>Offre</th>
					<th>Publié le</th>
					{# <th>Modifiée le</th> #}
				</tr>
			</thead>
			<tbody>

				{% for post in pagination %}
					<tr class="table-group-divider">
						<td class="fw-bold">
							<span class="badge bg-secondary rounded-pill">{{ post.id }}</span>
						</td>
						<td><a class="btn btn-outline-dark rounded-pill text-center fw-bold" href="{{ path('app_post_show', {'id': post.id}) }}">{{ post.title }}</a></td>
						{# <td>{{ post.resume }}</td> #}
						<td class="text-nowrap">{{ post.city.name }}</td>
						<td class="text-nowrap">{{ post.category.name }}</td>
						<td>{{ post.isActive ? 'Oui' : 'Non' }}</td>
						<td>{{ post.isOffer ? 'Oui' : 'Non' }}</td>
						<td>{{ post.publishedAt ? post.publishedAt|date('d-m-Y H:i') : '' }}</td>
						{# <td>{{ post.updatedAt ? post.updatedAt|date('d-m-Y H:i') : '' }}</td> #}
					</tr>
				{% else %}
					{% include "fragments/_no_entry_message.html.twig" %}
				{% endfor %}

			</tbody>
		</table>

		{% include "fragments/_pagination.html.twig" %}

	</div>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une publication
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mt-5">Ajouter une nouvelle publication</h1>

        {{ include('post/_form.html.twig') }}

        <a href="{{ path('app_post_index') }}" class="btn btn-secondary m-1 rounded-pill">Retour</a>
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication #
	{{ post.id }}
{% endblock %}

{% block body %}
	<div class="container col-6">
		<h1 class="mt-5 bg-secondary bg-gradient rounded-top-5 p-3 text-light text-center mb-0">Publication
			<span class="badge rounded-pill text-bg-success">{{ post.id }}</span>
		</h1>
		<table class="table table-borderless table-striped table-sm shadow text-center">
			<tbody>
				<tr>
					<th class="table-success">Titre</th>
					<td class="fw-bold">{{ post.title }}</td>
				</tr>
				<tr>
					<th class="table-success">Auteur</th>
					<td>{{ post.user.alias }}</td>
				</tr>
				<tr>
					<th class="table-success">Résumé</th>
					<td>{{ post.resume }}</td>
				</tr>
				<tr>
					<th class="table-success">Actif</th>
					<td>{{ post.isActive ? 'Oui' : 'Non' }}</td>
				</tr>
				<tr>
					<th class="table-success">Offre</th>
					<td>{{ post.isOffer ? 'Oui' : 'Non' }}</td>
				</tr>
				<tr>
					<th class="table-success">Publié le</th>
					<td>{{ post.publishedAt ? post.publishedAt|date('d-m-Y H:i') : '' }}</td>
				</tr>
				<tr>
					<th class="text-nowrap table-success">Modifié le</th>
					<td>{{ post.updatedAt ? post.updatedAt|date('d-m-Y H:i') : '' }}</td>
				</tr>
			</tbody>
		</table>
		<div class="dropdown">
			{% if is_granted('ROLE_ADMIN', post) %}
				<button class="btn btn-outline-primary m-1 btn-sm rounded-pill dropdown-toggle fw-bold" type="button" data-bs-toggle="dropdown" aria-expanded="false">
					Actions
				</button>
				<ul class="dropdown-menu rounded-4 p-1 text-center">
					<li>
						<a class="dropdown-item rounded-pill m-1 text-center" href="{{ path('app_post_edit', {'id': post.id}) }}">Modifier</a>
					</li>
					{{ include('post/_delete_form.html.twig') }}
				</ul>
			{% else %}
				{{ include('post/_delete_form.html.twig') }}
			{% endif %}
		</div>
		<a href="{{ path('app_post_index') }}" class="btn btn-secondary m-1 btn-sm rounded-pill">Retour</a>
	</div>
{% endblock %}